/**
 * SkillGro — Database Seed (native MongoDB driver, no mongoose)
 * Place in:  backend/seed.js
 * Run with:  node seed.js (from backend directory)
 */

require('dotenv').config({ path: './backend/.env' });
const { MongoClient, ObjectId } = require('mongodb');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/skillgro';
const DB_NAME   = 'skillgro';

const run = async () => {
  const client = new MongoClient(MONGO_URI);
  await client.connect();
  console.log('✅ Connected to MongoDB');

  const db = client.db(DB_NAME);

  // ── Clear existing collections ──────────────────────────────────────────
  await db.collection('instructors').deleteMany({});
  await db.collection('courses').deleteMany({});
  await db.collection('events').deleteMany({});
  await db.collection('blogs').deleteMany({});
  await db.collection('products').deleteMany({});
  console.log('🗑  Cleared old data');

  // ── Instructors ──────────────────────────────────────────────────────────
  const rfId = new ObjectId();
  const dmId = new ObjectId();
  const jwId = new ObjectId();
  const wwId = new ObjectId();

  await db.collection('instructors').insertMany([
    {
      _id: rfId,
      name: 'Robert Fox',
      slug: 'robert-fox',
      initials: 'RF',
      role: 'UX Design Lead',
      bio: 'Robert is a world-class UX designer with over a decade of experience working with Fortune 500 companies and leading startups. He is passionate about bridging the gap between beautiful design and functional interfaces that users love.\n\nBefore joining SkillGro as a lead instructor, Robert led design teams at several high-growth tech companies and won multiple industry awards for his product work.',
      avatarColor: 'linear-gradient(135deg,#a07cf8,#c0a0ff)',
      expertise: ['User Research', 'Interaction Design', 'Figma', 'Design Systems', 'Prototyping', 'Accessibility'],
      rating: 4.8,
      studentCount: 2100,
      courseCount: 12,
      social: { twitter: '@robertfox', linkedin: 'robertfox', website: 'robertfox.design' },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: dmId,
      name: 'David Millar',
      slug: 'david-millar',
      initials: 'DM',
      role: 'Web Development',
      bio: 'David is a full-stack developer and dedicated educator who has been building for the web for over 12 years. He has worked at leading tech companies and consulted for hundreds of businesses.\n\nHis teaching philosophy is simple: learn by building real things. Every one of his courses is project-based, so students graduate with a portfolio they are proud of.',
      avatarColor: 'linear-gradient(135deg,#00d4ff,#80eeff)',
      expertise: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'TypeScript', 'System Design'],
      rating: 4.9,
      studentCount: 3500,
      courseCount: 18,
      social: { twitter: '@davidmillar', linkedin: 'davidmillar', website: 'davidmillar.dev' },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: jwId,
      name: 'Jenny Wilson',
      slug: 'jenny-wilson',
      initials: 'JW',
      role: 'Graphic Design',
      bio: 'Jenny is an award-winning graphic designer, brand strategist, and creative director with 8+ years in the industry. She has helped over 200 brands develop their visual identity.\n\nHer courses focus on building a strong creative foundation — from typography and colour theory to full brand system design.',
      avatarColor: 'linear-gradient(135deg,#c8ff00,#e0ff80)',
      expertise: ['Brand Identity', 'Typography', 'Adobe Suite', 'Illustration', 'Color Theory', 'Print Design'],
      rating: 4.7,
      studentCount: 1800,
      courseCount: 9,
      social: { twitter: '@jennywilson', linkedin: 'jennywilson', website: 'jennywilson.co' },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: wwId,
      name: 'Wade Warren',
      slug: 'wade-warren',
      initials: 'WW',
      role: 'Digital Marketing',
      bio: 'Wade is a digital marketing strategist who has driven growth for dozens of DTC brands and SaaS companies. He specialises in paid social, SEO, and conversion optimisation.\n\nWith SkillGro, Wade brings his real-world campaign experience directly into the classroom, sharing the exact frameworks he uses with his agency clients.',
      avatarColor: 'linear-gradient(135deg,#f05c8a,#f090b0)',
      expertise: ['Facebook Ads', 'SEO', 'Email Marketing', 'Analytics', 'CRO', 'Growth Hacking'],
      rating: 4.5,
      studentCount: 2600,
      courseCount: 14,
      social: { twitter: '@wadewarren', linkedin: 'wadewarren', website: 'wadewarren.co' },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
  console.log('✅ Seeded 4 instructors');

  // ── Courses ──────────────────────────────────────────────────────────────
  await db.collection('courses').insertMany([
    {
      _id: new ObjectId(),
      title: 'Learning JavaScript With Imagination',
      slug: 'learning-javascript-with-imagination',
      shortDesc: 'Master modern JS from scratch with creative projects.',
      description: 'A comprehensive JavaScript course covering ES6+, async patterns, DOM manipulation, and real-world projects. Perfect for beginners and those looking to solidify their fundamentals. You will build real apps from day one and leave with a portfolio you are proud of.',
      emoji: '⚡',
      category: 'Development',
      level: 'Beginner',
      price: 29,
      originalPrice: 49,
      badge: 'Hot!',
      instructor: dmId,
      duration: '11h 20m',
      language: 'English',
      rating: 4.8,
      reviewCount: 342,
      enrolledCount: 1240,
      isPublished: true,
      whatYouLearn: [
        'Master ES6+ features including arrow functions and destructuring',
        'Build real-world projects from scratch',
        'Understand async/await and Promises',
        'DOM manipulation and event handling',
        'Work with APIs and fetch data',
        'Write clean, maintainable code',
      ],
      requirements: [
        'Basic HTML and CSS knowledge',
        'A computer with internet access',
        'No prior JavaScript experience needed',
      ],
      lessons: [
        { title: 'Introduction to JavaScript',  duration: '12:00', isFree: true,  order: 1 },
        { title: 'Variables, Types & Operators', duration: '18:30', isFree: true,  order: 2 },
        { title: 'Functions & Scope',            duration: '22:00', isFree: false, order: 3 },
        { title: 'Arrays & Objects',             duration: '25:00', isFree: false, order: 4 },
        { title: 'DOM Manipulation',             duration: '30:00', isFree: false, order: 5 },
        { title: 'Async JavaScript',             duration: '28:00', isFree: false, order: 6 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'The Complete Graphic Design for Beginners',
      slug: 'the-complete-graphic-design-for-beginners',
      shortDesc: 'From zero to professional designer in 70 hours.',
      description: 'Everything you need to become a professional graphic designer. Covers typography, color theory, layout, branding, and industry tools including Figma and Adobe Creative Suite. Build a full professional portfolio by the end of the course.',
      emoji: '🎨',
      category: 'Design',
      level: 'Beginner',
      price: 19,
      originalPrice: 39,
      badge: 'New',
      instructor: jwId,
      duration: '70h 45m',
      language: 'English',
      rating: 4.5,
      reviewCount: 128,
      enrolledCount: 875,
      isPublished: true,
      whatYouLearn: [
        'Typography principles and font pairing',
        'Color theory and brand design',
        'Layout and composition rules',
        'Figma from scratch',
        'Build a professional design portfolio',
        'Logo and brand identity design',
      ],
      requirements: [
        'No design experience needed',
        'Figma free account (we will set it up together)',
      ],
      lessons: [
        { title: 'Design Fundamentals',    duration: '15:00', isFree: true,  order: 1 },
        { title: 'Color Theory',           duration: '20:00', isFree: true,  order: 2 },
        { title: 'Typography Masterclass', duration: '22:00', isFree: false, order: 3 },
        { title: 'Layout & Composition',   duration: '18:00', isFree: false, order: 4 },
        { title: 'Logo Design in Figma',   duration: '35:00', isFree: false, order: 5 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Learning Digital Marketing on Facebook',
      slug: 'learning-digital-marketing-on-facebook',
      shortDesc: 'Master Facebook Ads and organic growth strategies.',
      description: 'A practical course on Facebook and Instagram marketing. Learn to run profitable ad campaigns, build audiences, and grow your brand organically with proven strategies used by top agencies worldwide.',
      emoji: '📣',
      category: 'Marketing',
      level: 'Intermediate',
      price: 15,
      originalPrice: 29,
      badge: 'Sale',
      instructor: wwId,
      duration: '18h 20m',
      language: 'English',
      rating: 4.3,
      reviewCount: 88,
      enrolledCount: 643,
      isPublished: true,
      whatYouLearn: [
        'Set up and run Facebook Ad campaigns',
        'Target the right audience with precision',
        'Build organic reach on Instagram',
        'Track and optimise campaign performance',
        'Retargeting and lookalike audiences',
      ],
      requirements: [
        'A Facebook account',
        'Basic understanding of social media',
      ],
      lessons: [
        { title: 'Facebook Ads Overview',      duration: '10:00', isFree: true,  order: 1 },
        { title: 'Setting Up Your Ad Account', duration: '15:00', isFree: true,  order: 2 },
        { title: 'Audience Targeting',         duration: '25:00', isFree: false, order: 3 },
        { title: 'Ad Creative & Copywriting',  duration: '22:00', isFree: false, order: 4 },
        { title: 'Analytics & Optimisation',   duration: '20:00', isFree: false, order: 5 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Financial Analyst Training & Investing Course',
      slug: 'financial-analyst-training-investing-course',
      shortDesc: 'Learn to analyze stocks and build an investment portfolio.',
      description: 'From reading financial statements to building a diversified investment portfolio. This course covers fundamental analysis, technical analysis, options, and personal finance planning.',
      emoji: '💰',
      category: 'Finance',
      level: 'All Levels',
      price: 24,
      originalPrice: null,
      badge: '',
      instructor: rfId,
      duration: '18h 20m',
      language: 'English',
      rating: 4.8,
      reviewCount: 217,
      enrolledCount: 921,
      isPublished: true,
      whatYouLearn: [
        'Read and interpret financial statements',
        'Perform fundamental stock analysis',
        'Build a diversified investment portfolio',
        'Understand technical analysis basics',
        'Manage personal finance and budgeting',
      ],
      requirements: [
        'No prior finance knowledge required',
        'Basic math skills',
      ],
      lessons: [
        { title: 'Introduction to Finance',      duration: '14:00', isFree: true,  order: 1 },
        { title: 'Reading Financial Statements',  duration: '28:00', isFree: true,  order: 2 },
        { title: 'Stock Valuation Methods',       duration: '32:00', isFree: false, order: 3 },
        { title: 'Building Your Portfolio',       duration: '26:00', isFree: false, order: 4 },
        { title: 'Risk Management',               duration: '20:00', isFree: false, order: 5 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Get Started With UI Design & Tips To Speed',
      slug: 'get-started-with-ui-design-tips-to-speed',
      shortDesc: 'Professional UI design workflows in Figma.',
      description: 'A hands-on UI design course focusing on design systems, component libraries, prototyping, and developer handoff using Figma. Learn the exact workflows used by product designers at top tech companies.',
      emoji: '📐',
      category: 'Design',
      level: 'Intermediate',
      price: 19,
      originalPrice: 32,
      badge: 'Hot!',
      instructor: rfId,
      duration: '11h 20m',
      language: 'English',
      rating: 5.0,
      reviewCount: 456,
      enrolledCount: 1823,
      isPublished: true,
      whatYouLearn: [
        'Build complete design systems in Figma',
        'Create reusable component libraries',
        'Prototype interactive flows',
        'Hand off designs to developers correctly',
        'Use auto-layout and variables',
      ],
      requirements: [
        'Basic Figma familiarity helpful but not required',
        'Free Figma account',
      ],
      lessons: [
        { title: 'Figma Interface Overview',  duration: '12:00', isFree: true,  order: 1 },
        { title: 'Components & Variants',     duration: '24:00', isFree: true,  order: 2 },
        { title: 'Auto Layout Mastery',       duration: '20:00', isFree: false, order: 3 },
        { title: 'Design Tokens & Variables', duration: '22:00', isFree: false, order: 4 },
        { title: 'Prototyping & Handoff',     duration: '18:00', isFree: false, order: 5 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Master the Fundamentals of Math',
      slug: 'master-the-fundamentals-of-math',
      shortDesc: 'Build a rock-solid foundation in mathematics.',
      description: 'Algebra, calculus, statistics, and logic — covering the mathematical foundations essential for data science, programming, and everyday problem solving.',
      emoji: '🧮',
      category: 'Mathematics',
      level: 'Beginner',
      price: 12,
      originalPrice: null,
      badge: '',
      instructor: dmId,
      duration: '70h 45m',
      language: 'English',
      rating: 4.7,
      reviewCount: 163,
      enrolledCount: 492,
      isPublished: true,
      whatYouLearn: [
        'Algebra from the ground up',
        'Introduction to calculus',
        'Statistics and probability',
        'Logic and proof techniques',
        'Apply math to real-world problems',
      ],
      requirements: [
        'Basic arithmetic only',
        'No calculus or advanced math needed',
      ],
      lessons: [
        { title: 'Numbers & Arithmetic Review', duration: '16:00', isFree: true,  order: 1 },
        { title: 'Algebra Foundations',         duration: '28:00', isFree: true,  order: 2 },
        { title: 'Introduction to Calculus',    duration: '35:00', isFree: false, order: 3 },
        { title: 'Statistics & Probability',    duration: '30:00', isFree: false, order: 4 },
        { title: 'Logic & Problem Solving',     duration: '22:00', isFree: false, order: 5 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
  console.log('✅ Seeded 6 courses');

  // ── Events ───────────────────────────────────────────────────────────────
  await db.collection('events').insertMany([
    {
      _id: new ObjectId(),
      title: 'Web Dev Conference 2025',
      slug: 'web-dev-conference-2025',
      description: 'Join 500+ developers for a full day of expert talks, hands-on workshops, and industry networking.\n\nSpeakers include senior engineers from Google, Vercel, and Cloudflare.',
      date: new Date('2025-09-15'),
      time: '9:00 AM – 6:00 PM',
      location: 'Javits Center, New York, USA',
      isOnline: false,
      isFree: false,
      price: 49,
      seats: 500,
      seatsLeft: 134,
      emoji: '💻',
      category: 'Development',
      badge: 'Featured',
      instructor: dmId,
      attendees: [],
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'UI/UX Design Masterclass',
      slug: 'ui-ux-design-masterclass',
      description: 'A deep-dive 3-hour online masterclass covering modern design systems and component libraries.\n\nYou will walk away with a reusable component library and the confidence to build scalable design systems.',
      date: new Date('2025-10-05'),
      time: '2:00 PM – 5:00 PM EST',
      location: 'Online (Zoom)',
      isOnline: true,
      isFree: true,
      price: 0,
      seats: 200,
      seatsLeft: 87,
      emoji: '🎨',
      category: 'Design',
      badge: 'Free',
      instructor: rfId,
      attendees: [],
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Digital Marketing Summit',
      slug: 'digital-marketing-summit',
      description: 'Two days of insights from top marketing leaders and growth hackers. Sessions cover paid social, SEO, email marketing, and conversion rate optimisation.',
      date: new Date('2025-11-10'),
      time: '10:00 AM – 4:00 PM',
      location: 'Los Angeles Convention Center, USA',
      isOnline: false,
      isFree: false,
      price: 79,
      seats: 300,
      seatsLeft: 45,
      emoji: '📣',
      category: 'Marketing',
      badge: 'Selling Fast',
      instructor: wwId,
      attendees: [],
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Data Science Bootcamp Online',
      slug: 'data-science-bootcamp-online',
      description: 'Intensive 2-day bootcamp covering Python, ML fundamentals, pandas, and data visualisation. Hands-on from the first minute.',
      date: new Date('2025-12-01'),
      time: '9:00 AM – 5:00 PM',
      location: 'Online (Zoom)',
      isOnline: true,
      isFree: false,
      price: 99,
      seats: 150,
      seatsLeft: 62,
      emoji: '📊',
      category: 'Data Science',
      badge: '',
      instructor: dmId,
      attendees: [],
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
  console.log('✅ Seeded 4 events');

  // ── Blog Posts ────────────────────────────────────────────────────────────
  await db.collection('blogs').insertMany([
    {
      _id: new ObjectId(),
      title: 'Top Web Development Trends to Watch in 2024',
      slug: 'top-web-dev-trends-2024',
      excerpt: 'From AI-assisted coding to edge-first architecture, here\'s what every developer needs to know this year.',
      content: 'The web development landscape is shifting faster than ever. In 2024, AI code assistants have moved from novelty to necessity.\n\nOn the architecture side, edge-first deployments are becoming the default. Frameworks like Next.js and Remix are making it easy to run logic at the CDN edge.\n\nServer components have matured. The mental model has clicked for most teams, and the performance benefits are measurable.\n\nFinally, TypeScript adoption has reached near-universal levels in professional teams.',
      emoji: '💻',
      category: 'Development',
      tags: ['javascript', 'react', 'web development', 'trends'],
      author: { name: 'David Millar', initials: 'DM', color: 'var(--cyan)' },
      readTime: '5 min',
      views: 1240,
      likes: 87,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: '7 UX Design Principles Every Designer Must Know',
      slug: 'ux-design-principles',
      excerpt: 'Great design isn\'t just about aesthetics—it\'s about creating experiences that feel effortless and intuitive.',
      content: 'Good UX design is invisible. When it works, users do not notice the design at all.\n\n1. Clarity above all. Every element on screen should have a clear purpose.\n\n2. Consistency builds trust. Users learn your interface once and expect it to behave the same way everywhere.\n\n3. Feedback for every action. Every click or tap should produce visible feedback.\n\n4. Error prevention over error recovery. Design to prevent mistakes from happening in the first place.\n\n5. Progressive disclosure. Show only what users need right now.\n\n6. Accessibility is not optional. It is the baseline.\n\n7. Test with real users. Your assumptions will be wrong in ways you cannot anticipate.',
      emoji: '🎨',
      category: 'Design',
      tags: ['ux', 'design', 'ui', 'principles'],
      author: { name: 'Robert Fox', initials: 'RF', color: 'var(--violet2)' },
      readTime: '4 min',
      views: 980,
      likes: 64,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'The Complete Beginner\'s Guide to Digital Marketing',
      slug: 'digital-marketing-beginners',
      excerpt: 'Master SEO, social media, email campaigns and paid ads with this comprehensive step-by-step guide.',
      content: 'Digital marketing encompasses all marketing efforts that use electronic devices or the internet. It\'s about reaching customers where they spend their time online.\n\nSEO Fundamentals: Search Engine Optimization is about making your website more visible in search results.\n\nSocial Media Marketing: Build community and engagement on platforms like Instagram, TikTok, and LinkedIn.\n\nEmail Marketing: Email remains one of the most effective marketing channels.\n\nPaid Advertising: Platforms like Google Ads and Facebook Ads allow you to reach specific audiences.',
      emoji: '📣',
      category: 'Marketing',
      tags: ['digital marketing', 'seo', 'social media', 'email'],
      author: { name: 'Wade Warren', initials: 'WW', color: 'var(--pink)' },
      readTime: '8 min',
      views: 1105,
      likes: 73,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'Why Python is Still King of Data Science in 2024',
      slug: 'python-data-science',
      excerpt: 'Despite new challengers, Python\'s ecosystem of libraries and community support keeps it at the top.',
      content: 'Python\'s data science stack is unparalleled. Libraries like pandas, NumPy, scikit-learn, and TensorFlow provide everything you need.\n\nThe Python community is vast and supportive. Stack Overflow, GitHub, and countless tutorials make it easy to find help.\n\nPython isn\'t just for data science. You can build web applications, automate tasks, and even create games.\n\nCompanies like Google, Netflix, and Spotify use Python extensively.',
      emoji: '📊',
      category: 'Data Science',
      tags: ['python', 'data science', 'machine learning'],
      author: { name: 'Cameron K.', initials: 'CK', color: 'var(--orange)' },
      readTime: '6 min',
      views: 756,
      likes: 52,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: 'How to Start Investing in Your 20s (Step-by-Step)',
      slug: 'investing-your-20s',
      excerpt: 'Time is your greatest asset. Here\'s how to make the most of compound interest and index funds starting today.',
      content: 'Starting early gives you the advantage of compound interest. Even small amounts invested regularly can grow significantly.\n\nBefore investing, build an emergency fund covering 3-6 months of expenses.\n\nIn your 20s, you have time to recover from market volatility. Focus on long-term growth.\n\nFor beginners, low-cost index funds and ETFs are excellent starting points.\n\nTake advantage of tax-advantaged retirement accounts.',
      emoji: '💰',
      category: 'Finance',
      tags: ['investing', 'finance', 'personal finance'],
      author: { name: 'Eleanor Pena', initials: 'EP', color: 'var(--violet)' },
      readTime: '7 min',
      views: 980,
      likes: 64,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      title: '10 Tips to Land Your First Freelance Design Client',
      slug: 'freelance-designer-tips',
      excerpt: 'From building your portfolio to writing cold outreach that actually gets replies — a practical playbook.',
      content: 'Your portfolio is your most important marketing tool. Showcase your best work and tell the story behind each project.\n\nSpecialize in a specific type of design work. This makes you more attractive to clients.\n\nUse professional email, have contracts ready, and set up proper invoicing.\n\nAttend design meetups, join online communities, and connect with other designers on LinkedIn.\n\nStart a blog, YouTube channel, or social media presence.\n\nResearch what similar designers charge.\n\nProposals should focus on the client\'s needs.\n\nGo above and beyond on your first projects.\n\nUse tools like time tracking and project management software.\n\nStay current with design trends and new tools.',
      emoji: '✨',
      category: 'Design',
      tags: ['freelance', 'design', 'business'],
      author: { name: 'Jenny Wilson', initials: 'JW', color: 'var(--lime)' },
      readTime: '5 min',
      views: 756,
      likes: 52,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
  console.log('✅ Seeded 6 blog posts');

  // ── Products ─────────────────────────────────────────────────────────────
  await db.collection('products').insertMany([
    {
      _id: new ObjectId(),
      name: 'UI Design Masterclass Bundle',
      slug: 'ui-design-masterclass-bundle',
      description: 'The ultimate all-in-one bundle for aspiring UI designers. Includes 40+ hours of video, Figma templates, UI kit components, and lifetime community access.\n\nEverything you need to go from visual principles to shipping production-grade design systems.',
      price: 129,
      originalPrice: 249,
      category: 'Design',
      emoji: '🎨',
      badge: 'Best Seller',
      rating: 4.9,
      reviewCount: 847,
      stock: 999,
      isDigital: true,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      name: 'Web Dev Pro Toolkit',
      slug: 'web-dev-toolkit',
      description: 'A comprehensive toolkit for professional developers. Includes a Next.js starter, 80+ React components, TypeScript utilities, and full documentation.\n\nBuilt to solve the real problems you face every day on the job.',
      price: 89,
      originalPrice: 179,
      category: 'Development',
      emoji: '🛠️',
      badge: 'Popular',
      rating: 4.8,
      reviewCount: 612,
      stock: 999,
      isDigital: true,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      name: 'Digital Marketing Playbook',
      slug: 'digital-marketing-playbook',
      description: 'A 200-page actionable PDF playbook covering Facebook Ads, Google Ads, SEO, and email marketing. Written from real agency experience.\n\nIncludes 30+ templates and the exact checklists used to manage millions in monthly ad spend.',
      price: 39,
      originalPrice: 79,
      category: 'Marketing',
      emoji: '📣',
      badge: 'New',
      rating: 4.7,
      reviewCount: 234,
      stock: 999,
      isDigital: true,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: new ObjectId(),
      name: 'Complete Investing Starter Kit',
      slug: 'complete-investing-starter-kit',
      description: 'Everything a beginner investor needs. Includes a portfolio spreadsheet, stock analysis template, budget planner, and a guide to index fund investing.\n\nAll templates in Excel and Google Sheets format with full instructions.',
      price: 49,
      originalPrice: 99,
      category: 'Finance',
      emoji: '💰',
      badge: '',
      rating: 4.6,
      reviewCount: 189,
      stock: 999,
      isDigital: true,
      isPublished: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
  console.log('✅ Seeded 4 products');

  await client.close();
  console.log('\n🎉 Database seeded successfully!');
  console.log('   Now start the backend:  cd backend && npm run dev');
};

run().catch(err => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
